package com.nierprotomata.game.view;

public enum Assets {
	WALL,
	GROUND,
	PLAYER_FULL_LIFE,
	PLAYER_FULL_LIFE_SHADOW,
	PLAYER_MID_LIFE,
	PLAYER_MID_LIFE_SHADOW,
	PLAYER_LOW_LIFE,
	PLAYER_LOW_LIFE_SHADOW,
	BULLET,
	BULLET_SHADOW,
	ENEMY1,
	RED_BULLET,
	PURPLE_BULLET,
	ENEMY1_EXPLOSION,
}
