package com.nierprotomata.game.view;

public enum Sounds {
	NEW_GAME,
	MENU_SELECTION,
	MENU_CONFIRMATION,
	MENU_BACK,
	PLAYER_SHOOT,
	PLAYER_DESTROY,
	ENEMY_SHOOT,
	ENEMY_HIT,
	ENEMY_BULLET_HIT_WALL,
	ENEMY_NORMAL_DESTROY,
	ENEMY_BOSS_DESTROY
}
